### ISSUE TITLE
Hii this is such a nice project and i want to contribute!!

### ISSUE THREAD

**Issue by LucaOll** [wosochart/TheWosoChart#1]
Hello I'm a fellow lesbian and also a bit into coding and want to contribute to your project. I want to add a relationship between Laura Freigang and Lena Mantler. Would you grant me the permisson, so that I can push on other branches but main? Then I would give you a pull request and you can decide if you want to merge it to the main branch :) I would be so delighted to contribute. You would see every change in a diff view and could approve or deny every change I add and you can also comment on it. I would be so glad, to be part of your project :) Thank you for maybe considering it and thanks 1 mio times for the effort you put in this really outstanding piece of lesbian history :D

**Comment by wosochart** [comment]
Hey! Thank you so much! Honestly I'm not rll confident that i can do all this, one of my friends made the code and did the github things, I do the google sheets so if you want I can make you a commenter on there and I would update it? That would help me all lot

**Comment by LucaOll** [comment]
Yeah that would also be great :) Thank youuuu. My email-address is luca.oldenburg@googlemail.com

**Comment by wosochart** [comment]
Done!
