### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by woso-enjoyer** [wosochart/TheWosoChart#2]
Hello,

I would like to contribute but it seems that you rely on some external spreadsheet from which you export the data. This makes it harder for anyone to submit a simple PR to the project to make changes.

Can you not just store the data in a JSON file within the project itself, and then we can just edit the JSON data ourselves when we want to make changes? I think that would be better for collaboration. You can still approve/deny any person's Pull Request, so the data will still be vetted by you

**Comment by wosochart** [comment]
I'm rll happy you want to contribute but I'm not rll confident with github or programming in general so I prefer it the way it is so it's easier for me. Thank you tho. You can always send me a message here or on tumblr about new information
